// Run with: npm test
//
// The chant JSON is generated by tools/chant-import from a PDF whose text is
// in two legacy font encodings with no ToUnicode map. Almost every way that
// import can go wrong is silent — a mis-mapped glyph produces perfectly
// plausible Devanagari, and a `normalized` field that drifts from
// normalize.ts leaves the matcher comparing against numbers nobody measured.
//
// So these tests are less about logic than about the data: that it is
// self-consistent, that it still agrees with the normaliser, and that no line
// is unmatchable.

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

import { allLines, flatten, renormalize, type Chant } from "./chant.ts";
import { cer, normalize } from "./normalize.ts";

const chant = JSON.parse(
  readFileSync(
    new URL("../../data/chants/sri-rudram-namakam-anuvaka-1.json", import.meta.url),
    "utf8",
  ),
) as Chant;

const lines = allLines(chant);

// --- the data agrees with the normaliser ------------------------------------

test("every line's normalized field is what normalize.ts produces", () => {
  // The load-bearing test in this file. build_chant.py writes this field using
  // tools/asr-bakeoff/normalize.py; if the two implementations ever diverge,
  // the app matches against one and the gate was measured with the other, and
  // nothing else anywhere fails.
  for (const line of lines) {
    assert.equal(
      renormalize(line),
      line.normalized,
      `line ${line.sequence} (${line.devanagari}) normalizes to ` +
        `"${renormalize(line)}" but the JSON says "${line.normalized}" — ` +
        `re-run tools/chant-import/build_chant.py`,
    );
  }
});

test("normalising is idempotent over the whole chant", () => {
  for (const line of lines) {
    assert.equal(normalize(line.normalized), line.normalized);
  }
});

// --- the data is well-formed ------------------------------------------------

test("sequence numbers run 1..N with no gaps or repeats", () => {
  assert.ok(lines.length > 0, "no lines at all");
  lines.forEach((line, i) => assert.equal(line.sequence, i + 1));
});

test("verse numbers start at 1 and never go backwards", () => {
  let previous = 0;
  for (const line of lines) {
    assert.ok(
      line.verse >= previous,
      `line ${line.sequence} is in verse ${line.verse}, after ${previous}`,
    );
    previous = line.verse;
  }
  assert.equal(lines[0].verse, 1);
});

test("no line is empty in any field the app renders", () => {
  for (const line of lines) {
    assert.ok(line.devanagari.trim(), `line ${line.sequence} has no text`);
    assert.ok(line.transliteration.trim(), `line ${line.sequence} has no IAST`);
    assert.ok(line.normalized, `line ${line.sequence} normalizes to nothing`);
  }
});

test("the decoder left no unmapped glyphs behind", () => {
  // decode_pdf.py emits "<0x1234>" for a code point missing from its font map
  // rather than dropping it. That placeholder must never reach the JSON.
  for (const line of lines) {
    assert.doesNotMatch(
      line.devanagari,
      /<[0-9a-f]{4}>/i,
      `line ${line.sequence} still contains a decoder placeholder`,
    );
  }
});

test("the Devanagari is Devanagari, with no Latin left in it", () => {
  // The source fonts encode Devanagari as Latin bytes, so a decoding miss
  // shows up as stray Latin rather than as a crash.
  for (const line of lines) {
    assert.doesNotMatch(
      line.devanagari,
      /[A-Za-z]/,
      `line ${line.sequence} has undecoded Latin: ${line.devanagari}`,
    );
  }
});

test("the Devanagari keeps its svara marks", () => {
  // The whole reason to decode this PDF rather than retype the text is the
  // accent notation. If a rule change ever strips it on import, say so loudly.
  const accented = lines.filter((l) => /[॒॑᳚]/.test(l.devanagari));
  assert.ok(
    accented.length > lines.length / 2,
    `only ${accented.length}/${lines.length} lines carry svara marks`,
  );
});

test("svara marks come last in their syllable, so nothing is orphaned", () => {
  // The source font draws the accent as soon as its glyph is reached, so
  // "नमः॑" is stored as न म ॑ ः. Unicode wants the accent after every matra,
  // virama, anusvara and visarga in the syllable, and NFC will not fix the
  // order because visarga is a spacing mark of combining class 0.
  //
  // Left wrong it is not a crash and not mojibake — the visarga becomes an
  // orphan and the shaper draws it on a dotted circle, so the page renders
  // नम॑◌ः. Easy to scroll straight past.
  for (const line of lines) {
    assert.doesNotMatch(
      line.devanagari,
      /[॒॑᳚][ंःािीुूृॄेैोौ्]/u,
      `line ${line.sequence} has an accent before the rest of its syllable, ` +
        `which renders on a dotted circle: ${line.devanagari}`,
    );
  }
});

test("the transliteration has no svara marks leaking into it", () => {
  // sanscript passes ॑ and ॒ through untouched, and they then combine with
  // whatever Latin letter follows: नमस्ते॑ renders as "namastḙ".
  for (const line of lines) {
    assert.doesNotMatch(
      line.transliteration.normalize("NFD"),
      /[॒॑᳚]/,
      `line ${line.sequence} transliterates to ${line.transliteration}`,
    );
  }
});

test("text is NFC, so identical strings compare equal", () => {
  for (const line of lines) {
    assert.equal(line.devanagari, line.devanagari.normalize("NFC"));
    assert.equal(line.normalized, line.normalized.normalize("NFC"));
  }
});

// --- the data is actually matchable -----------------------------------------

test("no two lines normalize to the same string", () => {
  // Two identical normalised lines are indistinguishable to the matcher, so
  // it could never do better than a coin flip between them.
  const seen = new Map<string, number>();
  for (const line of lines) {
    const clash = seen.get(line.normalized);
    assert.equal(
      clash,
      undefined,
      `lines ${clash} and ${line.sequence} both normalize to ` +
        `"${line.normalized}"`,
    );
    seen.set(line.normalized, line.sequence);
  }
});

test("no line normalizes down to a stub too short to match", () => {
  // A 5-second window holds roughly a line. Anything under about ten
  // characters would match half the chant equally well.
  for (const line of lines) {
    assert.ok(
      line.normalized.length >= 10,
      `line ${line.sequence} normalizes to only ${line.normalized.length} ` +
        `chars: "${line.normalized}"`,
    );
  }
});

test("lines are far enough apart to be told apart", () => {
  // Consistency is worthless without discriminability. The model's own
  // measured stability is 0.095, so any two lines closer than that are inside
  // its noise floor and cannot be separated by this approach.
  const worst = { a: 0, b: 0, score: 1 };
  for (let i = 0; i < lines.length; i++) {
    for (let j = i + 1; j < lines.length; j++) {
      const score = cer(lines[i].normalized, lines[j].normalized);
      if (score < worst.score) {
        worst.a = lines[i].sequence;
        worst.b = lines[j].sequence;
        worst.score = score;
      }
    }
  }
  assert.ok(
    worst.score > 0.095,
    `lines ${worst.a} and ${worst.b} differ by only ` +
      `${worst.score.toFixed(3)}, inside the model's own 0.095 stability`,
  );
});

// --- flattening -------------------------------------------------------------

test("flatten maps every character back to the line it came from", () => {
  const flat = flatten(chant);
  assert.equal(flat.text.length, flat.lineAt.length);
  assert.equal(flat.lines.length, lines.length);

  // Walk the boundaries: the slice each line claims must be its own text.
  let at = 0;
  flat.lines.forEach((line, index) => {
    const slice = flat.text.slice(at, at + line.normalized.length);
    assert.equal(slice, line.normalized, `line ${line.sequence} misplaced`);
    assert.equal(flat.lineAt[at], index, `start of line ${line.sequence}`);
    assert.equal(
      flat.lineAt[at + line.normalized.length - 1],
      index,
      `end of line ${line.sequence}`,
    );
    at += line.normalized.length;
  });
  assert.equal(at, flat.text.length);
});

test("flatten adds no characters between lines", () => {
  const joined = lines.map((l) => l.normalized).join("");
  assert.equal(flatten(chant).text, joined);
});

test("UTF-16 indices agree with code points across the chant", () => {
  // flatten indexes by UTF-16 unit while cer() compares by code point. Those
  // only agree while every character stays out of the astral planes, which is
  // true of Devanagari and the Vedic marks — but not of anything a future
  // chant might drag in.
  const flat = flatten(chant);
  assert.equal([...flat.text].length, flat.text.length);
});

// --- provenance -------------------------------------------------------------

test("the chant declares where it came from", () => {
  assert.match(chant.source.edition, /Sathya Sai/);
  assert.equal(chant.source.file, "Rudram_1st_anuvaka.pdf");
  assert.equal(chant.normalization.deaspirate, true);
});
