"""Generate the fixture that pins the TypeScript normaliser to this one.

    uv run python dump_vectors.py

There are two implementations of the same nine rules — normalize.py here, and
src/lib/chant/normalize.ts in the app — and they have to agree character for
character. The gate in Chunk 3 was measured with *this* one, so any divergence
means the browser is matching against numbers that were never measured, silently.

Rather than trusting two hand-written ports to stay in step, this writes the
Python output to a fixture the TypeScript test reads. Re-run it whenever a rule
changes; if the TS test then fails, the port needs the same change.

The inputs are mostly real: actual transcripts from the bake-off runs, actual
reference text with svara marks, plus one deliberate case per rule and the
degenerate inputs (empty, whitespace, punctuation-only) where an off-by-one in
either implementation would hide.
"""

from __future__ import annotations

import json
from pathlib import Path

from normalize import cer, normalize

FIXTURE = (
    Path(__file__).resolve().parents[2]
    / "src" / "lib" / "chant" / "normalize-vectors.json"
)

CASES: list[str] = [
    # --- real vak-san output on Rudram Test 1, at several window offsets
    "तेरुध्रमन्यव उत्तोत् ईशवेनमः नमस्ते",
    "रुध्रमन्यव उत्तोत् ईशवेनमः नमस्ते",
    "ुध्रमन्यव उत्तोत् ईशवेनमः नमस्ते अ",
    "ध्रमन्यव उत्तोत् ईशवेनमः नमस्ते अश्",
    "तेरुध्रमन्यव उत्तोत् ईशवेनमह नमस्ते",  # the int8 export's one difference
    "बाहोभ्याभुद्बुथतेन मः",
    "बाहोभ्याभुद्बुथतेनमः",
    # --- a different model on the same audio, so the fixture is not one voice
    "नमसते ऋध्रमन्यव उत्तोत ईशवे नमह नमस्ते असतु धनवने बाहो भयाभुताते नमह",
    "नमस्ति रुदरिमन्यम् उत्तुटयश्वे नमेन् नमस्ति अस्तु धन्ने बाहुद्यामुच्ते नमेन्",
    # --- romanised Whisper output: the case that made case-folding load-bearing
    "namasti rudra",
    "NAMASTE RUDR",
    "Namaste Rudra Manyava",
    # --- reference text, svara marks and danda included
    "नमस्ते॑ रुद्र म॒न्यव॑ उतो॒त इष॑वे नमः॑ ।",
    "नमस्ते अस्तु धन्वने बाहुभ्यामुत ते नमः ॥",
    "या ते॑ रुद्र शि॒वा त॒नूरघो॒राऽपा॑पकाशिनी ।",
    # --- one case per rule
    "शष स",  # sibilants
    "ङञणम ं ँ",  # nasals, including the two that a bad svara range swallowed
    "नमः",  # visarga
    "आईऊॠ ाीूॄ",  # vowel length
    "खघछझठढथधफभ",  # aspiration
    "क़ख़ग़ज़ड़ढ़फ़य़ऩऱऴ",  # nukta
    "ऩ",  # bare combining nukta
    "नमो नमः  नमो   नमः",  # whitespace collapse
    "१२३ 456 ।॥.,;:!?",  # digits and punctuation
    "ऽ",  # avagraha — in no rule, must survive untouched
    "ॐ",  # om — likewise
    "ऀ",  # inverted candrabindu — still deleted as a svara mark
    # --- degenerate
    "",
    "   ",
    "।॥",
    "\t\n ",
    # --- NFC: the same text decomposed and precomposed must agree
    "नि",  # नि as two code points
]

# Pairs for the distance function, chosen so a wrong normalisation-by-code-unit
# or a transposed min() in the Levenshtein loop shows up as a number.
PAIRS: list[tuple[str, str]] = [
    ("", ""),
    ("अ", ""),
    ("", "अ"),
    ("अ", "अ"),
    ("अ", "इ"),
    ("नमस्ते", "नमस्ते"),
    ("नमस्ते", "ननस्ते"),
    ("नमस्ते", "नमस्त"),
    ("नमस्ते", "मनस्ते"),  # transposition costs two edits, not one
    ("तेरुद्रनन्यव", "रुद्रनन्यव"),
    ("नन", "नन्"),
    ("abc", "xyz"),
]


def main() -> int:
    payload = {
        "_comment": (
            "Generated by tools/asr-bakeoff/dump_vectors.py — do not edit by "
            "hand. Pins src/lib/chant/normalize.ts to normalize.py, the "
            "implementation the Chunk 3 gate was measured with."
        ),
        "normalize": [
            {
                "input": case,
                "deaspirated": normalize(case),
                "kept": normalize(case, deaspirate=False),
            }
            for case in CASES
        ],
        "cer": [{"a": a, "b": b, "cer": cer(a, b)} for a, b in PAIRS],
    }
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
    print(
        f"wrote {FIXTURE.relative_to(Path(__file__).resolve().parents[2])}  "
        f"({len(CASES)} normalize cases, {len(PAIRS)} cer pairs)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
